version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Authorize
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project satakuntatalo-services
            gcloud --quiet config set compute/zone europe-west1
          only-branch: master
      - run:
          name: Deploy
          command: >
            gcloud functions deploy telegram-bot
            --region europe-west1
            --runtime python37
            --source https://source.developers.google.com/projects/satakuntatalo-services/repos/github_osakunta_telegram-bot
            --entry-point telegram_bot
            --memory 256MB
            --trigger-http
          only-branch: master
